WITH CTE AS 
(SELECT A.ID, A.NAME AS EMPLOYEE , A.SALARY , A.DEPARTMENTID,
B.NAME,
DENSE_RANK() OVER (PARTITION BY B.NAME ORDER BY A.SALARY DESC) AS RANKING
FROM EMPLOYEE AS A
LEFT JOIN
DEPARTMENT AS B
ON A.DEPARTMENTID = B.ID)

SELECT NAME AS DEPARTMENT,
EMPLOYEE, SALARY
FROM CTE
WHERE RANKING = 1
