WITH TempWeather AS (
    SELECT 
        ID, 
        RECORDDATE, 
        TEMPERATURE, 
        LAG(TEMPERATURE) OVER (ORDER BY RECORDDATE, ID) AS TEMP_1,
        LAG(RECORDDATE) OVER (ORDER BY RECORDDATE, ID) AS PREV_DATE
    FROM WEATHER
)
SELECT ID 
FROM TempWeather
WHERE TEMP_1 IS NOT NULL 
AND TEMP_1 < TEMPERATURE 
AND PREV_DATE=DATEADD(DAY, -1, recordDate)
ORDER BY RECORDDATE;


