WITH CTE AS
(SELECT
A.ID,A.NAME AS EMPLOYEE, A.SALARY , A.DEPARTMENTID,B.NAME AS DEPARTMENT,
DENSE_RANK() OVER(PARTITION BY B.NAME ORDER BY A.SALARY DESC) AS RANKING
FROM EMPLOYEE AS A
LEFT JOIN
DEPARTMENT AS B
ON A.DEPARTMENTID = B.ID)

SELECT
DEPARTMENT , EMPLOYEE , SALARY
FROM CTE
WHERE RANKING IN(1,2,3);